version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.gpu
      platform: linux/amd64
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - ENV=production
    ports:
      - "8000:8000"
    command: python main.py
